// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prova.Infra.Context;

namespace Prova.Infra.Migrations
{
    [DbContext(typeof(ProvaContext))]
    partial class ProvaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0") 
                .HasAnnotation("MySql:MaxIdentifierLength", 64) 
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prova.DomainModel.Entity.Contato", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("DataNascimento");

                b.Property<string>("Documento")
                    .IsRequired()
                    .HasColumnType("varchar(14)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.ToTable("Contato");
            });
#pragma warning restore 612, 618
        }
    }
}
